'use client';

import { useParams } from 'next/navigation';
import { useState, useEffect } from 'react';

// Format markdown content for better display
function formatMarkdownContent(content: string): string {
  return content
    // Headers
    .replace(/^### (.*$)/gim, '<h3 style="color: #1F2937; font-size: 20px; font-weight: 600; margin: 24px 0 12px 0; border-bottom: 2px solid #E5E7EB; padding-bottom: 8px;">$1</h3>')
    .replace(/^## (.*$)/gim, '<h2 style="color: #111827; font-size: 24px; font-weight: 700; margin: 32px 0 16px 0; border-bottom: 3px solid #6A3EE8; padding-bottom: 12px;">$1</h2>')
    .replace(/^# (.*$)/gim, '<h1 style="color: #111827; font-size: 28px; font-weight: 800; margin: 40px 0 20px 0; text-align: center; background: linear-gradient(135deg, #6A3EE8, #8B5CF6); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">$1</h1>')
    
    // Bold text
    .replace(/\*\*(.*?)\*\*/g, '<strong style="color: #1F2937; font-weight: 700;">$1</strong>')
    
    // Italic text
    .replace(/\*(.*?)\*/g, '<em style="color: #4B5563; font-style: italic;">$1</em>')
    
    // Lists
    .replace(/^\* (.*$)/gim, '<li style="margin: 8px 0; padding-left: 8px; position: relative;"><span style="color: #6A3EE8; font-weight: bold; position: absolute; left: -16px;">•</span>$1</li>')
    .replace(/^- (.*$)/gim, '<li style="margin: 8px 0; padding-left: 8px; position: relative;"><span style="color: #6A3EE8; font-weight: bold; position: absolute; left: -16px;">•</span>$1</li>')
    
    // Wrap lists in ul tags
    .replace(/(<li.*<\/li>)/g, '<ul style="margin: 16px 0; padding-left: 20px; background: #F9FAFB; border-left: 4px solid #6A3EE8; padding: 16px 20px; border-radius: 8px;">$1</ul>')
    
    // Code blocks
    .replace(/```([\s\S]*?)```/g, '<pre style="background: #1F2937; color: #F9FAFB; padding: 20px; border-radius: 8px; overflow-x: auto; margin: 16px 0; font-family: \'Monaco\', \'Menlo\', monospace; font-size: 14px; line-height: 1.5;"><code>$1</code></pre>')
    
    // Inline code
    .replace(/`([^`]+)`/g, '<code style="background: #F3E8FF; color: #6A3EE8; padding: 2px 6px; border-radius: 4px; font-family: \'Monaco\', \'Menlo\', monospace; font-size: 14px;">$1</code>')
    
    // Paragraphs
    .replace(/^(?!<[h|u|l|p])(.*$)/gim, '<p style="margin: 16px 0; line-height: 1.8;">$1</p>')
    
    // Remove empty paragraphs
    .replace(/<p><\/p>/g, '')
    
    // Clean up multiple newlines
    .replace(/\n{3,}/g, '\n\n');
}

export default function AIContentPage() {
  const params = useParams();
  const [content, setContent] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Extract content from URL or localStorage
    const slug = params.slug as string;
    const decodedSlug = decodeURIComponent(slug);
    const contentKey = `ai-content-${decodedSlug}`;
    console.log('Original slug:', slug);
    console.log('Decoded slug:', decodedSlug);
    console.log('Looking for AI content with key:', contentKey);
    console.log('Available localStorage keys:', Object.keys(localStorage).filter(k => k.startsWith('ai-content')));
    
    const storedContent = localStorage.getItem(contentKey);
    console.log('Stored content found:', !!storedContent);
    console.log('Stored content length:', storedContent?.length);
    
    if (storedContent) {
      try {
        const parsedContent = JSON.parse(storedContent);
        console.log('Parsed content:', parsedContent);
        setContent(parsedContent);
      } catch (error) {
        console.error('Error parsing stored content:', error);
        setContent({
          title: 'AI Generated Content',
          content: 'Error loading AI generated content.',
          source: 'AI Generated'
        });
      }
    } else {
      // If no stored content, show a message
      console.log('No stored content found, showing fallback');
      setContent({
        title: 'AI Generated Content',
        content: 'This content was generated by AI but is not available.',
        source: 'AI Generated'
      });
    }
    setLoading(false);
  }, [params.slug]);

  if (loading) {
    return (
      <div style={{
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        height: '100vh',
        fontSize: '18px'
      }}>
        Loading AI generated content...
      </div>
    );
  }

  return (
    <div style={{
      maxWidth: '800px',
      margin: '0 auto',
      padding: '40px 20px',
      fontFamily: 'Baloo Bhai, sans-serif'
    }}>
      <div style={{
        background: 'linear-gradient(135deg, #6A3EE8 0%, #8B5CF6 100%)',
        color: 'white',
        padding: '30px',
        borderRadius: '12px',
        marginBottom: '30px',
        textAlign: 'center'
      }}>
        <h1 style={{
          fontSize: '28px',
          fontWeight: 'bold',
          margin: '0 0 10px 0'
        }}>
          {content?.title || 'AI Generated Content'}
        </h1>
        <p style={{
          fontSize: '16px',
          opacity: 0.9,
          margin: 0
        }}>
          {content?.source || 'AI Generated'}
        </p>
      </div>

      <div style={{
        background: 'white',
        padding: '30px',
        borderRadius: '12px',
        boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
        lineHeight: '1.6',
        fontSize: '16px'
      }}>
        {content?.type === 'podcast' ? (
          <div>
            <div style={{
              background: '#F3E8FF',
              padding: '20px',
              borderRadius: '8px',
              marginBottom: '20px',
              textAlign: 'center'
            }}>
              <h3 style={{ margin: '0 0 10px 0', color: '#7C3AED' }}>🎧 Podcast Episode</h3>
              <p style={{ margin: 0, color: '#6B7280' }}>
                Duration: {content?.duration_minutes || 20} minutes
              </p>
            </div>
            
            <div style={{
              background: '#F8FAFC',
              padding: '20px',
              borderRadius: '8px',
              marginBottom: '20px'
            }}>
              <h4 style={{ margin: '0 0 15px 0', color: '#1F2937' }}>Podcast Script</h4>
              <div style={{
                whiteSpace: 'pre-wrap',
                color: '#374151',
                fontFamily: 'monospace',
                fontSize: '14px',
                lineHeight: '1.5'
              }}>
                {content?.content || 'Podcast script not available.'}
              </div>
            </div>
            
            <div style={{
              background: '#EFF6FF',
              padding: '20px',
              borderRadius: '8px',
              textAlign: 'center'
            }}>
              <p style={{ margin: '0 0 15px 0', color: '#1E40AF' }}>
                <strong>Listen to the podcast:</strong> Click below to hear the full audio version.
              </p>
              <button
                onClick={() => {
                  console.log('Opening TTS URL for podcast...');
                  const ttsUrl = `/api/tts?text=${encodeURIComponent(content?.content || '')}&voice=en-US-Standard-A`;
                  console.log('TTS URL:', ttsUrl);
                  window.open(ttsUrl, '_blank', 'width=800,height=600,scrollbars=yes,resizable=yes');
                }}
                style={{
                  background: '#3B82F6',
                  color: 'white',
                  border: 'none',
                  padding: '12px 24px',
                  borderRadius: '6px',
                  fontSize: '16px',
                  fontWeight: '600',
                  cursor: 'pointer',
                  marginRight: '10px'
                }}
              >
                🎧 Listen to Podcast
              </button>
              <button
                onClick={() => {
                  console.log('Quick play button clicked');
                  if ('speechSynthesis' in window) {
                    console.log('Speech synthesis available, creating utterance...');
                    const utterance = new SpeechSynthesisUtterance(content?.content || '');
                    utterance.rate = 0.9;
                    utterance.pitch = 1;
                    utterance.volume = 1;
                    
                    utterance.onstart = () => console.log('Speech started');
                    utterance.onend = () => console.log('Speech ended');
                    utterance.onerror = (e) => console.error('Speech error:', e);
                    
                    speechSynthesis.speak(utterance);
                    console.log('Speech synthesis speak() called');
                  } else {
                    console.log('Speech synthesis not supported');
                    alert('Text-to-speech not supported in this browser');
                  }
                }}
                style={{
                  background: '#10B981',
                  color: 'white',
                  border: 'none',
                  padding: '12px 24px',
                  borderRadius: '6px',
                  fontSize: '16px',
                  fontWeight: '600',
                  cursor: 'pointer'
                }}
              >
                🔊 Quick Play
              </button>
            </div>
          </div>
        ) : (
          <div 
            style={{
              color: '#374151',
              lineHeight: '1.8',
              fontSize: '16px'
            }}
            dangerouslySetInnerHTML={{
              __html: formatMarkdownContent(content?.content || 'Content not available.')
            }}
          />
        )}
      </div>

      <div style={{
        marginTop: '30px',
        textAlign: 'center'
      }}>
        <button
          onClick={() => window.history.back()}
          style={{
            background: '#6A3EE8',
            color: 'white',
            border: 'none',
            padding: '12px 24px',
            borderRadius: '8px',
            fontSize: '16px',
            fontWeight: '600',
            cursor: 'pointer',
            transition: 'background-color 0.2s ease'
          }}
          onMouseOver={(e) => (e.target as HTMLButtonElement).style.background = '#5a2d91'}
          onMouseOut={(e) => (e.target as HTMLButtonElement).style.background = '#6A3EE8'}
        >
          ← Back to Roadmap
        </button>
      </div>
    </div>
  );
}
