'use client';

import { useParams } from 'next/navigation';
import { useState, useEffect } from 'react';

export default function AIContentPage() {
  const params = useParams();
  const [content, setContent] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Extract content from URL or localStorage
    const slug = params.slug as string;
    const contentKey = `ai-content-${slug}`;
    const storedContent = localStorage.getItem(contentKey);
    
    if (storedContent) {
      setContent(JSON.parse(storedContent));
    } else {
      // If no stored content, show a message
      setContent({
        title: 'AI Generated Content',
        content: 'This content was generated by AI but is not available.',
        source: 'AI Generated'
      });
    }
    setLoading(false);
  }, [params.slug]);

  if (loading) {
    return (
      <div style={{
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        height: '100vh',
        fontSize: '18px'
      }}>
        Loading AI generated content...
      </div>
    );
  }

  return (
    <div style={{
      maxWidth: '800px',
      margin: '0 auto',
      padding: '40px 20px',
      fontFamily: 'Baloo Bhai, sans-serif'
    }}>
      <div style={{
        background: 'linear-gradient(135deg, #6A3EE8 0%, #8B5CF6 100%)',
        color: 'white',
        padding: '30px',
        borderRadius: '12px',
        marginBottom: '30px',
        textAlign: 'center'
      }}>
        <h1 style={{
          fontSize: '28px',
          fontWeight: 'bold',
          margin: '0 0 10px 0'
        }}>
          {content?.title || 'AI Generated Content'}
        </h1>
        <p style={{
          fontSize: '16px',
          opacity: 0.9,
          margin: 0
        }}>
          {content?.source || 'AI Generated'}
        </p>
      </div>

      <div style={{
        background: 'white',
        padding: '30px',
        borderRadius: '12px',
        boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
        lineHeight: '1.6',
        fontSize: '16px'
      }}>
        <div style={{
          whiteSpace: 'pre-wrap',
          color: '#374151'
        }}>
          {content?.content || 'Content not available.'}
        </div>
      </div>

      <div style={{
        marginTop: '30px',
        textAlign: 'center'
      }}>
        <button
          onClick={() => window.history.back()}
          style={{
            background: '#6A3EE8',
            color: 'white',
            border: 'none',
            padding: '12px 24px',
            borderRadius: '8px',
            fontSize: '16px',
            fontWeight: '600',
            cursor: 'pointer',
            transition: 'background-color 0.2s ease'
          }}
          onMouseOver={(e) => e.target.style.background = '#5a2d91'}
          onMouseOut={(e) => e.target.style.background = '#6A3EE8'}
        >
          ← Back to Roadmap
        </button>
      </div>
    </div>
  );
}
